/**
 * SendGrid Integration
 * Send email notifications and campaigns
 */

import { APIClient } from "./api-client";

export interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
}

export interface EmailResult {
  success: boolean;
  messageId: string;
  recipient: string;
}

export class SendGridIntegration {
  private client: APIClient;

  constructor(apiKey: string) {
    this.client = new APIClient({
      baseURL: "https://api.sendgrid.com/v3",
      headers: {
        Authorization: `Bearer ${apiKey}`,
      },
    });
  }

  /**
   * Send a single email
   */
  async sendEmail(
    to: string,
    subject: string,
    htmlContent: string,
    fromEmail: string = "noreply@yourdomain.com",
  ): Promise<EmailResult> {
    const response = await this.client.post("/mail/send", {
      personalizations: [
        {
          to: [{ email: to }],
          subject: subject,
        },
      ],
      from: {
        email: fromEmail,
        name: "SIM-OPS Alerts",
      },
      content: [
        {
          type: "text/html",
          value: htmlContent,
        },
      ],
    });

    return {
      success: response.status === 202,
      messageId: response.headers["x-message-id"] || "",
      recipient: to,
    };
  }

  /**
   * Send retention campaign email
   */
  async sendRetentionEmail(
    customerEmail: string,
    customerName: string,
    discountCode?: string,
  ): Promise<EmailResult> {
    const subject = "We'd love to keep you as a customer";
    const html = `
      <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
          <h2>Hi ${customerName},</h2>
          <p>We noticed you might be considering leaving us. We'd love to keep you!</p>
          ${discountCode ? `<p><strong>Here's a special offer just for you: ${discountCode}</strong></p>` : ""}
          <p>If there's anything we can do to improve your experience, please let us know.</p>
          <a href="https://yourdomain.com/contact" style="background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Contact Us</a>
          <p>Best regards,<br>Your Team</p>
        </body>
      </html>
    `;

    return this.sendEmail(customerEmail, subject, html);
  }

  /**
   * Send alert notification to team
   */
  async sendAlertEmail(
    recipients: string[],
    alertTitle: string,
    alertDetails: string,
    severity: "low" | "medium" | "high" | "critical",
  ): Promise<EmailResult[]> {
    const severityColors = {
      low: "#28a745",
      medium: "#ffc107",
      high: "#fd7e14",
      critical: "#dc3545",
    };

    const html = `
      <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
          <div style="border-left: 4px solid ${severityColors[severity]}; padding-left: 15px;">
            <h2 style="color: ${severityColors[severity]}; margin: 0;">
              ${severity.toUpperCase()} ALERT: ${alertTitle}
            </h2>
            <p style="margin-top: 10px;">${alertDetails}</p>
            <p style="color: #666; font-size: 12px;">
              Generated by SIM-OPS at ${new Date().toLocaleString()}
            </p>
          </div>
          <a href="https://yourdomain.com/dashboard" style="display: inline-block; margin-top: 20px; background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">
            View Dashboard
          </a>
        </body>
      </html>
    `;

    const results: EmailResult[] = [];
    for (const recipient of recipients) {
      const result = await this.sendEmail(
        recipient,
        `[${severity.toUpperCase()}] ${alertTitle}`,
        html,
      );
      results.push(result);
    }

    return results;
  }

  /**
   * Send bulk campaign
   */
  async sendBulkCampaign(
    recipients: Array<{ email: string; name: string }>,
    subject: string,
    htmlContent: string,
  ): Promise<{ sent: number; failed: number }> {
    let sent = 0;
    let failed = 0;

    // SendGrid allows batch sending
    const personalizations = recipients.map((recipient) => ({
      to: [{ email: recipient.email, name: recipient.name }],
      subject: subject,
    }));

    try {
      await this.client.post("/mail/send", {
        personalizations,
        from: {
          email: "campaigns@yourdomain.com",
          name: "Your Company",
        },
        content: [
          {
            type: "text/html",
            value: htmlContent,
          },
        ],
      });
      sent = recipients.length;
    } catch (error) {
      failed = recipients.length;
    }

    return { sent, failed };
  }
}

/**
 * Usage Example:
 * 
 * const sendgrid = new SendGridIntegration(process.env.SENDGRID_API_KEY!);
 * 
 * // In Action Agent - Send retention email
 * await sendgrid.sendRetentionEmail(
 *   'customer@example.com',
 *   'John Doe',
 *   'SAVE20'
 * );
 * 
 * // In Monitoring Agent - Send alert
 * await sendgrid.sendAlertEmail(
 *   ['team@company.com'],
 *   'High Churn Rate Detected',
 *   'Churn rate has exceeded 5% threshold',
 *   'high'
 * );
 * 
 * // In Action Agent - Bulk campaign
 * await sendgrid.sendBulkCampaign(
 *   atRiskCustomers,
 *   'Special Offer Inside',
 *   campaignHTML
 * );
 */
